### ISSUE TITLE
Restructure Build Targets

### ISSUE THREAD

**Issue by ratuspro** [GameDevTecnico/cubos#41]
The building pipeline should be able to generate:

- **cubos-core (library)** - includes all the core modules of the engine that will be used by the systems. This should be easily testable
- **cubos (executable)** - links `cubos-core` with an `entrypoint` that is responsible to load all assets into a game. Also includes all the systems necessary to execute the game (e.g. rendering, input, etc...)
- **cubos-editor (executable)** - a standalone application that links `cubos-core` and helps creating assets that will then be loaded by `cubos`

**Comment by RicardoEPRodrigues** [comment]
I would suggest the following:

* cubos-core -> cubos-engine - this naming is more understandable since other engines use this, although Unreal Engine splits the engine into multiple smaller libraries, so `core` would make sense if you plan on doing the same.
* cubos -> cubos-application - this makes it clear that it is an application that can be run, otherwise you are sending conflicting information. Is `cubos` an engine or an application?

**Comment by RiscadoA** [comment]
`cubos` is the actual engine, maybe it should be named `cubos-engine`.

**Comment by RiscadoA** [comment]
I suggest the following file structure:
```
core/
  include/
  src/
  lib/
  tests/
  samples/
  CMakeLists.txt
engine/
  src/
  CMakeLists.txt
editor/
  src/
  include/
  CMakeLists.txt
CMakeLists.txt
```

**Comment by ratuspro** [comment]
Yap, I think it makes sense to add the editor down the road.
