### ISSUE TITLE
Settings serialization

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#48]
Depends on #15.
Implement loading and storing settings.

**Comment by joaopat98** [comment]
Add interface for basic types (doubles, strings, etc.), stored as strings. When getting, if not able to convert, return type default.

**Comment by ratuspro** [comment]
> When getting, if not able to convert, return type default.

I did something different:
- When there is a setting with the key and can return the requested type, returns the stored value.
- When there is a setting with the key and cannot return the requested type, raises an exception.
- When there is no setting with the key, returns the default value

It helps the game developer to identify errors easily since it does not hide them by returning the default value.

**Comment by ratuspro** [comment]
Solved on #104

**Comment by joaopat98** [comment]
@ratuspro
